name: Build Windows installer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Якщо є lockfile — ставимо Node з кешем
      - name: Setup Node (with cache)
        if: ${{ hashFiles('**/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Якщо lockfile НЕТ — ставимо Node без кешу (щоб не падало)
      - name: Setup Node (no cache)
        if: ${{ hashFiles('**/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        shell: pwsh
        run: |
          if (Test-Path "package-lock.json") {
            npm ci
          } else {
            npm install
          }


      - name: Build
        shell: pwsh
        run: npm run build

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: PixelBar-Setup
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
            dist/*.7z
            dist/*.blockmap
          if-no-files-found: error
