name: Build Windows installer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        shell: pwsh
        run: |
          if (Test-Path "package-lock.json") {
            Write-Host "Found package-lock.json → running npm ci"
            npm ci
          } else {
            Write-Host "No lockfile → running npm install"
            npm install
          }

      - name: Show versions
        run: |
          node -v
          npm -v
          npx tsc -v

      - name: Build (Vite + Electron + pack)
        run: npm run build

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: PixelBar-Setup
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
            dist/*.7z
            dist/*.blockmap
          if-no-files-found: error
